version: '3.8'

services:
  robotics-academy:
    image: jderobot/robotics-backend:4.6.4
    container_name: user_container
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "7164:7164"
      - "6080:6080"
      - "1108:1108"
      - "7163:7163"
    tty: true
    stdin_open: true
